PUT http://localhost:3003/api/blogs/6a4b935552641abad009ee6e
Content-Type: application/json

{
  "title": "Tehtävät 5.5 ja 5.6 toimivat",
  "author": "Ron Gustafsson",
  "url": "http://www.testi.com",
  "likes": 1
}